

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_ASTEROIDS = 7
ASTEROID_MIN_SPEED= 40

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 100
MAX_PLAYER_SPEED = 1000
PLAYER_ACCELERATION = 50
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5
SHOT_COOLDOWN =0.3
MAX_SHOTS=5